### ISSUE TITLE
Grading Overview

### ISSUE THREAD

**Issue by Lucav17** [kjscott27/ColmarAcademy#1]
### Criteria 1: HTML Structure  
* _Score Level:_  4
* _Comment(s):_  Great HTML structure! You had great indentation, good comments, and overall good HTML.
 
### Criteria 2: Visual Layout for Both Desktop and Mobile Sizes
* _Score Level:_ 4
* _Comment(s):_ Great job using your CSS skills to render on both mobile and desktop.
 
### Criteria 3: Responsive Design (Media Queries, Responsive Units, etc.)
* _Score Level:_ 4
* _Comment(s):_ Same as above! You showed great CSS skills
 
### Criteria 4: Visual Design and Accessibility (Color Palette, Typography, Transitions, etc.)
* _Score Level:_ 4
* _Comment(s):_ Overall I think you did a great job visually on the site. 
 
### Overall Score: 16/16
Well done!

**Comment by kjscott27** [comment]
Thank you very much for the feedback Luca! It was great fun creating this project.
